//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "orders")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub fromevmtosol: bool,
    pub maker: String,
    pub receiver: String,
    pub token0: String,
    pub token1: String,
    pub token0amount: i64,
    pub token1amount: i64,
    pub timestart: Decimal,
    pub timeendl: Decimal,
    pub tx_hash_solana: String,
    pub tx_hash_evm: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
