//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "solana_tokens")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub mint: String,
    pub name: String,
    pub decimals: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::token_relations::Entity")]
    TokenRelations,
}

impl Related<super::token_relations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TokenRelations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
