//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "token_relations")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub evm_token_id: i32,
    pub solana_token_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::evm_tokens::Entity",
        from = "Column::EvmTokenId",
        to = "super::evm_tokens::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    EvmTokens,
    #[sea_orm(has_many = "super::orders::Entity")]
    Orders,
    #[sea_orm(
        belongs_to = "super::solana_tokens::Entity",
        from = "Column::SolanaTokenId",
        to = "super::solana_tokens::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SolanaTokens,
}

impl Related<super::evm_tokens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EvmTokens.def()
    }
}

impl Related<super::orders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Orders.def()
    }
}

impl Related<super::solana_tokens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SolanaTokens.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
